"""Table Rencontre,categorie et jointure + rename de insciption

Revision ID: 93d500e10f13
Revises: 4791773e1845
Create Date: 2026-09-17 16:59:10.572094

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '93d500e10f13'
down_revision: Union[str, Sequence[str], None] = '4791773e1845'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.rename_table('inscription','inscriptions')
    op.create_table('rencontres',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_tournament', sa.Integer(), nullable=False),
    sa.Column('id_user_blanc', sa.Integer(), nullable=False),
    sa.Column('id_user_noir', sa.Integer(), nullable=False),
    sa.Column('ronde', sa.Integer(), nullable=False),
    sa.Column('resultat', sa.Enum('Blanc', 'Noir', 'Equalite', 'PasJoue', name='resulats'), nullable=False),
    sa.ForeignKeyConstraint(['id_tournament'], ['tournaments.id'], ),
    sa.ForeignKeyConstraint(['id_user_blanc'], ['users.id'], ),
    sa.ForeignKeyConstraint(['id_user_noir'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tournaments_categories',
    sa.Column('id_categorie', sa.Integer(), nullable=False),
    sa.Column('id_tournament', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_categorie'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['id_tournament'], ['tournaments.id'], ),
    sa.PrimaryKeyConstraint('id_categorie', 'id_tournament')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tournaments_categories')
    op.drop_table('rencontres')
    op.rename_table('inscriptions','inscription')
    op.drop_table('categories')
    sa.Enum('Blanc', 'Noir', 'Equalite', 'PasJoue', name='resulats').drop(op.get_bind())
    # ### end Alembic commands ###
