"""Table tournament + inscription

Revision ID: 4791773e1845
Revises: 75d7312aaefa
Create Date: 2026-09-17 15:13:46.678780

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4791773e1845'
down_revision: Union[str, Sequence[str], None] = '75d7312aaefa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tournaments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(), nullable=False),
    sa.Column('lieu', sa.String(), nullable=False),
    sa.Column('inscript_min', sa.Integer(), nullable=False),
    sa.Column('inscript_max', sa.Integer(), nullable=False),
    sa.Column('elo_min', sa.Integer()),
    sa.Column('elo_max', sa.Integer()),
    sa.Column('status', sa.Enum('EnAttente', 'EnCours', 'Termine', name='status'), nullable=False),
    sa.Column('ronde', sa.Integer(), nullable=False),
    sa.Column('women_only', sa.Boolean(), nullable=False),
    sa.Column('date_de_creation', sa.DateTime(), nullable=False),
    sa.Column('date_de_fin_inscription', sa.DateTime(), nullable=False),
    sa.Column('date_de_derniere_mise_a_jour', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_check_constraint('TOURNAMENT_ELO_CK','tournaments',condition='COALESCE(elo_min) <= COALESCE(elo_max)')
    op.create_check_constraint('TOURNAMENT_ELO_MIN_CK','tournaments',condition='COALESCE(elo_min,0) >= 0')
    op.create_check_constraint('TOURNAMENT_ELO_MAX_CK','tournaments',condition='COALESCE(elo_max,3000) <= 3000')
    op.create_check_constraint('TOURNAMENT_INSCRIPTION_CK','tournaments',condition='inscript_min <= inscript_max')
    op.create_check_constraint('TOURNAMENT_INSCRIPTION_MIN_CK','tournaments',condition='inscript_min >= 2')
    op.create_check_constraint('TOURNAMENT_INSCRIPTION_MAX_CK','tournaments',condition='inscript_max <= 32')
    op.create_check_constraint('TOURNAMENT_DATE_CK','tournaments',condition='EXTRACT( DAY FROM (date_de_fin_inscription - date_de_creation)) <= COALESCE(inscript_min,2)')

    op.create_table('inscription',
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.Column('id_tournament', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_tournament'], ['tournaments.id'], ),
    sa.ForeignKeyConstraint(['id_user'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id_user', 'id_tournament')
    )
    op.add_column('users', sa.Column('date_de_naissance', sa.DateTime(), nullable=False))
    op.add_column('users', sa.Column('allow_mail', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'allow_mail')
    op.drop_column('users', 'date_de_naissance')
    op.drop_table('inscription')
    op.drop_table('tournaments')
    # ### end Alembic commands ###
