"""patch field lieu to be nullable

Revision ID: 4a2f494dab17
Revises: 9540e5f49708
Create Date: 2026-09-21 11:59:05.730355

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a2f494dab17'
down_revision: Union[str, Sequence[str], None] = '9540e5f49708'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tournaments', 'lieu',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tournaments', 'lieu',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
