"""insert junior,senior,veteran

Revision ID: 2b7ad7b9303f
Revises: 3e6ac439fdda
Create Date: 2026-09-21 14:36:47.672480

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2b7ad7b9303f'
down_revision: Union[str, Sequence[str], None] = '3e6ac439fdda'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("INSERT INTO CATEGORIES values (1,'junior',0,17)")
    op.execute("INSERT INTO CATEGORIES values (2,'senior',18,59)")
    op.execute("INSERT INTO CATEGORIES values (3,'veteran',60,999)")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DELETE FROM CATEGORIES WHERE id=1")
    op.execute("DELETE FROM CATEGORIES WHERE id=2")
    op.execute("DELETE FROM CATEGORIES WHERE id=3")
    # ### end Alembic commands ###
