"""change DATE_CK

Revision ID: 2367d2b3ee9c
Revises: 4a2f494dab17
Create Date: 2026-09-21 12:03:11.190808

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2367d2b3ee9c'
down_revision: Union[str, Sequence[str], None] = '4a2f494dab17'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('TOURNAMENT_DATE_CK','tournaments')
    op.create_check_constraint('TOURNAMENT_DATE_CK','tournaments',
        condition='EXTRACT( DAY FROM (date_de_fin_inscription - date_de_creation)) >= inscript_min')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('TOURNAMENT_DATE_CK','tournaments')
    op.create_check_constraint('TOURNAMENT_DATE_CK','tournaments',condition='EXTRACT( DAY FROM (date_de_fin_inscription - date_de_creation)) <= inscript_min')
    # ### end Alembic commands ###
