"""add age min and max to categorie

Revision ID: 3e6ac439fdda
Revises: 2367d2b3ee9c
Create Date: 2026-09-21 14:35:42.671625

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e6ac439fdda'
down_revision: Union[str, Sequence[str], None] = '2367d2b3ee9c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('age_min', sa.Integer(), nullable=False))
    op.add_column('categories', sa.Column('age_max', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('categories', 'age_max')
    op.drop_column('categories', 'age_min')
    # ### end Alembic commands ###
